name: simple-streamlit
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - python-dotenv
    - streamlit
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly==5.19.0
    - statsmodels==0.14.2
    - tensorflow==2.16.1
    - scikit-learn
    - scipy